name: Matt
role: Design Engineer
intro:
  - I currently work at HKUST AIS, where I lead the brand design of the faculty.
  - I co-founded Incipe Academy. A better Arduino for plug and play hardware
    prototyping. Setting the new standard in hardware-software communication.
  - I co-design with C-levels from 2-Sigma, McKinsey, ToyZeroPlus to achieve
    their private ventures. I also work with startup to build their foundation
    through good design.
  - I consider myself a designer and enjoy building highly polished products to
    connect people's heart.
socials:
  - label: LinkedIn
    url: https://www.linkedin.com/in/mattmatt-mm/
  - label: Github
    url: https://github.com/mattmatt-mm
email: 0701mattmatt@gmail.com
