name: Matt
role: Design Engineer
intro:
  - I have just finished leading the brand design for HKUST AIS, the faculty's
    school branding.
  - I co-founded Incipe Academy and OCAT Robotics. Bringing AI into the
    physical world.
  - I co-design digital experiences for high-profile clients' private
    ventures. I also enjoy leading a team to turn our visions into products.
  - I consider myself a designer and enjoy building highly polished products to
    connect people's heart.
socials:
  - label: LinkedIn
    url: https://www.linkedin.com/in/mattmatt-mm/
  - label: Github
    url: https://github.com/mattmatt-mm
email: 0701mattmatt@gmail.com
